units:
  # board config

  # Proxy Spacing Variables
  key_width: cx
  key_height: cy

  mcu_width: 18
  mcu_height: 33

  # Padding between mcu and keys
  mcu_padding_width:  2.5
  mcu_padding_height:  2.5

  # Board Outline Padding
  outline_width: key_width + 2
  outline_height: key_height + 2

  # web-ui overrides to better see overlaping choc keys
  $default_width: 18 - 0.5
  $default_height: 17 - 0.5

points:
  mirror: &mirror
    ref: finger-zone_pinky_top
    distance: -1.2 * outline_width

  zones:
    # Finger rows
    finger-zone:
      anchor:
        shift: [230, -160] # fixing kicad placement
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        pinky:
          key:
            column_net: P18
        ring:
          key:
            stagger: 14
            splay: -7
            spread: 20
            column_net: P15
        middle:
          key:
            stagger: 8
            column_net: P14
        index:
          key:
            stagger: -10
            column_net: P16
        inner:
          key:
            stagger: -3
            column_net: P10
      rows:
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6

    # Thumb cluster
    thumb-zone:
      anchor:
        ref: finger-zone_inner_bottom # ref to a key zone_column_row
        shift: [0 - 6, -1 * key_height - 5]
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        inner:
          key:
            splay: -15
            column_net: P16
        outer:
          key:
            splay: -12
            shift: [4, -2]
            column_net: P10
      rows:
        sole:
          row_net: P9


outlines:
  raw:
    - what: rectangle
      where: true
      size: [mcu_padding_width, mcu_padding_height]

  keys:
    - what: rectangle
      where: true
      bound: false
      size: [key_width - 0.5, key_height - 0.5]

  fill-left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: finger-zone_pinky_top
          shift: [-0.5 * outline_width, 0.5 * outline_height]

        - ref: finger-zone_pinky_top
          shift: [0.5 * outline_width + key_width, 0.5 * outline_height]
        
        - ref: finger-zone_inner_home
          shift: [-0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, key_height]
        - ref: finger-zone_inner_home
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, key_height]

        - ref: finger-zone_inner_bottom
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, -0.5 * key_height]

        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, 0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [-0.5 * outline_width, -0.5 * outline_height]

        - ref: thumb-zone_inner_sole
          shift: [-.5 * outline_width, -0.5 * outline_height]

        - ref: finger-zone_pinky_bottom
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: finger-zone_pinky_bottom
          shift: [-0.5 * outline_width, -0.5 * outline_height]
  
  fill-right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_finger-zone_pinky_top
          shift: [-0.5 * outline_width, 0.5 * outline_height]

        - ref: mirror_finger-zone_pinky_top
          shift: [0.5 * outline_width + key_width, 0.5 * outline_height]
        
        - ref: mirror_finger-zone_inner_home
          shift: [-0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, key_height]
        - ref: mirror_finger-zone_inner_home
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, key_height]

        - ref: mirror_finger-zone_inner_bottom
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, -0.5 * key_height]

        - ref: mirror_thumb-zone_outer_sole
          shift: [0.5 * outline_width, 0.5 * outline_height]
        - ref: mirror_thumb-zone_outer_sole
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: mirror_thumb-zone_outer_sole
          shift: [-0.5 * outline_width, -0.5 * outline_height]

        - ref: mirror_thumb-zone_inner_sole
          shift: [-.5 * outline_width, -0.5 * outline_height]

        - ref: mirror_finger-zone_pinky_bottom
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: mirror_finger-zone_pinky_bottom
          shift: [-0.5 * outline_width, -0.5 * outline_height]

  fill:
    - name: fill-left
    - operation: add
      name: fill-right

  keys_outline:
    - what: rectangle
      where: true
      bound: false
      size: [outline_width, outline_height]
      corner: 2

  board:
    - name: keys_outline
    - operation: add
      name: fill

  complete:
    - name: board
    - operation: stack
      name: keys

pcbs:
  dyad-choc-v1:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        asym: both
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      mcu-left:
        what: nicenano
        params:
          orientation: "down"
          RAW: RAW
          GND1: GND
          RST: RST
          VCC: VCC
          P21: P21
          P20: P20
          P19: P19
          P18: P18
          P15: P15
          P14: P14
          P16: P16
          P10: P10
          CS: CS
          P0: P0
          GND2: GND
          GND3: GND
          MOSI: MOSI
          SCK: SCK
          P4: P4
          P5: P5
          P6: P6
          P7: P7
          P8: P8
          P9: P9
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width, -1]
          rotate: -90


      mcu-right:
        what: nicenano
        params:
          orientation: "down"
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, -1]
          rotate: 90

      battery-left: # todo sort to and from
        what: battery
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, 15.5]
          rotate: 90
        

      battery-right: # todo sort to and from
        what: battery
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, 15.5]
          rotate: -90

      power-switch-left: # todo sort to and from
        what: slider_reversible
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, 15.5]
        params:
          side: B
          reverse: false
          from: RAW
          to: POSITIVE

      power-switch-right: # todo sort to and from
        what: slider_reversible
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, 15.5]
        params:
          side: B
          reverse: false
          from: RAW
          to: POSTIVE

      nice-view-left:
        what: niceview
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, -20.5]
        adjust:
          rotate: 90
        params:
          outline: true
          side: 'F'
          MOSI: MOSI
          SCK: SCK
          VCC: VCC
          GND: GND
          CS: CS
      
      nice-view-right:
        what: niceview
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, -20.5]
        adjust:
          rotate: -90
        params:
          outline: true
          side: 'F'
          MOSI: MOSI
          SCK: SCK
          VCC: VCC
          GND: GND
          CS: CS
      
      reset-left:
        what: b3u1000p
        where:
          - ref: finger-zone_inner_home
            shift: [key_width + mcu_padding_width, -30.5]
            rotate: 180
        params:
          r1: RST
          r2: GND
          reverse: false

      reset-right:
        what: b3u1000p
        where:
          - ref: mirror_finger-zone_inner_home
            shift: [key_width + mcu_padding_width, -30.5]
            rotate: -180
        params:
          r1: RST
          r2: GND
          reverse: false

      via-gnd:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width, -50.5]
        params:
          net: RAW