units:
  # board config

  # Proxy Spacing Variables
  key_width: cx
  key_height: cy

  # MCU dimensions
  mcu_width: 18
  mcu_height: 33

  # Padding between mcu and keys
  mcu_padding_width:  2.5
  mcu_padding_height:  2.5

  # starting height of MCU reletive to home row
  mcu_position_height: -5

  # Board Outline Padding
  outline_width: key_width + 2
  outline_height: key_height + 2

  # web-ui overrides to better see overlaping choc keys
  $default_width: 18 - 0.5
  $default_height: 17 - 0.5

points:
  zones:
    # Finger rows
    finger-zone:
      anchor:
        shift: [160, -160] # fixing kicad placement
        rotate: 7
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        pinky:
          key:
            column_net: COL0
        ring:
          key:
            stagger: 14
            splay: -7
            spread: 20
            column_net: COL1
        middle:
          key:
            stagger: 8
            column_net: COL2
        index:
          key:
            stagger: -10
            column_net: COL3
        inner:
          key:
            stagger: -3
            column_net: COL4
      rows:
        bottom:
          row_net: ROW2
        home:
          row_net: ROW1
        top:
          row_net: ROW0

    # Thumb cluster
    thumb-zone:
      anchor:
        ref: finger-zone_inner_bottom # ref to a key zone_column_row
        shift: [0 - 6, -1 * key_height - 2.5]
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        inner:
          key:
            splay: -15
            column_net: COL3
        outer:
          key:
            splay: -12
            shift: [4, -2]
            column_net: COL4
      rows:
        sole:
          row_net: ROW3


outlines:
  raw:
    - what: rectangle
      where: true
      size: [mcu_padding_width, mcu_padding_height]

  keys:
    - what: rectangle
      where: true
      bound: false
      size: [key_width - 0.5, key_height - 0.5]

  fill:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: finger-zone_pinky_top
          shift: [-0.5 * outline_width, 0.5 * outline_height]

        - ref: finger-zone_pinky_top
          shift: [0.5 * outline_width + key_width, 0.5 * outline_height]
        
        - ref: finger-zone_inner_home
          shift: [-0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]
        - ref: finger-zone_inner_home
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]

        - ref: finger-zone_inner_bottom
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, -0.5 * key_height]

        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, 0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [-0.5 * outline_width, -0.5 * outline_height]

        - ref: thumb-zone_inner_sole
          shift: [-.5 * outline_width, -0.5 * outline_height]

        - ref: finger-zone_pinky_bottom
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: finger-zone_pinky_bottom
          shift: [-0.5 * outline_width, -0.5 * outline_height]

  keys_outline:
    - what: rectangle
      where: true
      bound: false
      size: [outline_width, outline_height]
      corner: 2

  board:
    - name: keys_outline
    - operation: add
      name: fill

  complete:
    - name: board
    - operation: stack
      name: keys

pcbs:
  socius-choc-v1:
    outlines:
      main:
        outline: board
    footprints:

      choc_hotswap:
        what: choc_V1_V2
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: smd-diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -4.8]

      via-diode-1:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-1.6, -3.3]

      via-diode-2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [1.6, -3.3]

      via-row:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-4, -3.3]
        
      via-column-2:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [-3.2, 2]

      mcu:
        what: nicenano
        params:
          # orientation: "down"
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height -1]
          rotate: -90

      battery:
        what: battery
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
          rotate: -90

      power-switch:
        what: slider_reversible
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
        params:
          side: B
          reverse: true
          from: RAW
          to: POSITIVE
      
      reset:
        what: b3u1000p
        where:
          - ref: finger-zone_inner_home
            shift: [key_width + mcu_padding_width, mcu_position_height -23]
            rotate: 180
        params:
          r1: GND
          r2: RST
          reverse: true

      # Reversable MCU
      via-raw-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 12.7]
        params:
          net: RAW

      via-raw-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 12.7]
        params:
          net: RAW

      via-cs-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 11.65]
        params:
          net: CS

      via-cs-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 11.65]
        params:
          net: CS

      via-gnd1-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 10.45]
        params:
          net: GND

      via-gnd1-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 10.45]
        params:
          net: GND

      via-p0-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 9.4]
        params:
          net: P0

      via-p0-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 9.4]
        params:
          net: P0

      via-rst-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 7.91]
        params:
          net: RST

      via-rst-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 7.91]
        params:
          net: RST

      via-gnd2-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 6.86]
        params:
          net: GND

      via-gnd2-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 6.86]
        params:
          net: GND

      via-vcc-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 5.37]
        params:
          net: VCC

      via-vcc-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 5.37]
        params:
          net: VCC

      via-gnd3-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 4.32]
        params:
          net: GND

      via-gnd3-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 4.32]
        params:
          net: GND

      via-p21-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 2.83]
        params:
          net: P21

      via-p21-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 2.83]
        params:
          net: P21

      via-mosi-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 1.78]
        params:
          net: MOSI

      via-mosi-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 1.78]
        params:
          net: MOSI

      via-p20-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height + 0.29]
        params:
          net: P20

      via-p20-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height + 0.29]
        params:
          net: P20

      via-sck-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 0.76]
        params:
          net: SCK

      via-sck-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 0.76]
        params:
          net: SCK

      via-p19-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 2.25]
        params:
          net: P19

      via-p19-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 2.25]
        params:
          net: P19

      via-p4-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 3.3]
        params:
          net: P4

      via-p4-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 3.3]
        params:
          net: P4

      via-col0-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 4.79]
        params:
          net: COL0

      via-col0-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 4.79]
        params:
          net: COL0

      via-p5-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 5.84]
        params:
          net: P5

      via-p5-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 5.84]
        params:
          net: P5

      via-col1-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 7.33]
        params:
          net: COL1

      via-col1-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 7.33]
        params:
          net: COL1

      via-row0-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 8.38]
        params:
          net: ROW0

      via-row0-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 8.38]
        params:
          net: ROW0

      via-col2-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 9.87]
        params:
          net: COL2

      via-col2-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 9.87]
        params:
          net: COL2

      via-row1-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 10.92]
        params:
          net: ROW1

      via-row1-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 10.92]
        params:
          net: ROW1

      via-col3-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 12.41]
        params:
          net: COL3

      via-col3-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 12.41]
        params:
          net: COL3

      via-row2-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 13.46]
        params:
          net: ROW2

      via-row2-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 13.46]
        params:
          net: ROW2

      via-col4-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 14.95]
        params:
          net: COL4

      via-col4-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 14.95]
        params:
          net: COL4

      via-row3-pin-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.8, mcu_position_height - 16]
        params:
          net: ROW3

      via-row3-pin-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.8, mcu_position_height - 16]
        params:
          net: ROW3


      # MCU
      # via-gnd-1: 
      #   what: via
      #   where:
      #     ref: finger-zone_inner_home
      #     shift: [key_width + mcu_padding_width + 5.8, mcu_position_height + 9.2]
      #   params:
      #     net: GND

      # via-gnd-2:
      #   what: via
      #   where:
      #     ref: finger-zone_inner_home
      #     shift: [key_width + mcu_padding_width + 2.6, mcu_position_height + 9.2]
      #   params:
      #     net: GND

      # # via-row0-1:
      # #   what: via
      # #   where:
      # #     ref: finger-zone_inner_home
      # #     shift: [key_width + mcu_padding_width + 4.3, mcu_position_height + 11.52]
      # #   params:
      # #     net: ROW0

      # via-row0-2:
      #   what: via
      #   where:
      #     ref: finger-zone_inner_home
      #     shift: [key_width + mcu_padding_width + 4.3, mcu_position_height - 7.3]
      #   params:
      #     net: ROW0

      # via-row1-1:
      #   what: via
      #   where:
      #     ref: finger-zone_inner_home
      #     shift: [key_width + mcu_padding_width + 5.8, mcu_position_height + 1.6]
      #   params:
      #     net: ROW1

      via_reset-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.4, mcu_position_height - 23]
        params:
          net: RST

      via-reset-2: 
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.4, mcu_position_height - 23]
        params:
          net: GND
