units:
  # board config

  # Proxy Spacing Variables
  key_width: cx
  key_height: cy

  mcu_width: 18
  mcu_height: 33

  # Padding between mcu and keys
  mcu_padding_width:  2.5
  mcu_padding_height:  2.5

  # starting height of MCU reletive to home row
  mcu_position_height: -5

  # Board Outline Padding
  outline_width: key_width + 2
  outline_height: key_height + 2

  # web-ui overrides to better see overlaping choc keys
  $default_width: 18 - 0.5
  $default_height: 17 - 0.5

points:
  # mirror:
  #   ref: finger-zone_pinky_top
  #   distance: -1.2 * outline_width
  zones:
    # Finger rows
    finger-zone:
      mirror:
        ref: finger-zone_pinky_top
        distance: -1.2 * outline_width
      anchor:
        shift: [230, -160] # fixing kicad placement
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        pinky:
          key:
            column_net: COL0
        ring:
          key:
            stagger: 14
            splay: -7
            spread: 20
            column_net: COL1
        middle:
          key:
            stagger: 8
            column_net: COL2
        index:
          key:
            stagger: -10
            column_net: COL3
        inner:
          key:
            stagger: -3
            column_net: COL4
      rows:
        bottom:
          row_net: ROW2
        home:
          row_net: ROW1
        top:
          row_net: ROW0

    # Thumb cluster
    thumb-zone:
      mirror:
          ref: finger-zone_pinky_top
          distance: -1.2 * outline_width
      anchor:
        ref: finger-zone_inner_bottom # ref to a key zone_column_row
        shift: [0 - 6, -1 * key_height - 2.5]
      key:
        padding: key_height  # vertical spacing between keys
        spread: key_width   # horizontal spacing between keys
      columns:
        inner:
          key:
            splay: -15
            column_net: COL3
        outer:
          key:
            splay: -12
            shift: [4, -2]
            column_net: COL4
      rows:
        sole:
          row_net: ROW3


outlines:
  raw:
    - what: rectangle
      where: true
      size: [mcu_padding_width, mcu_padding_height]

  keys:
    - what: rectangle
      where: true
      bound: false
      size: [key_width - 0.5, key_height - 0.5]

  fill-left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: finger-zone_pinky_top
          shift: [-0.5 * outline_width, 0.5 * outline_height]

        - ref: finger-zone_pinky_top
          shift: [0.5 * outline_width + key_width, 0.5 * outline_height]
        
        - ref: finger-zone_inner_home
          shift: [-0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]
        - ref: finger-zone_inner_home
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]

        - ref: finger-zone_inner_bottom
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, -0.5 * key_height]

        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, 0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: thumb-zone_outer_sole
          shift: [-0.5 * outline_width, -0.5 * outline_height]

        - ref: thumb-zone_inner_sole
          shift: [-.5 * outline_width, -0.5 * outline_height]

        - ref: finger-zone_pinky_bottom
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: finger-zone_pinky_bottom
          shift: [-0.5 * outline_width, -0.5 * outline_height]
  
  fill-right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_finger-zone_pinky_top
          shift: [-0.5 * outline_width, 0.5 * outline_height]

        - ref: mirror_finger-zone_pinky_top
          shift: [0.5 * outline_width + key_width, 0.5 * outline_height]
        
        - ref: mirror_finger-zone_inner_home
          shift: [-0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]
        - ref: mirror_finger-zone_inner_home
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, mcu_position_height + key_height]

        - ref: mirror_finger-zone_inner_bottom
          shift: [0.5 * key_width + mcu_padding_width + 0.5 * (outline_width - key_width) + mcu_width, -0.5 * key_height]

        - ref: mirror_thumb-zone_outer_sole
          shift: [0.5 * outline_width, 0.5 * outline_height]
        - ref: mirror_thumb-zone_outer_sole
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: mirror_thumb-zone_outer_sole
          shift: [-0.5 * outline_width, -0.5 * outline_height]

        - ref: mirror_thumb-zone_inner_sole
          shift: [-.5 * outline_width, -0.5 * outline_height]

        - ref: mirror_finger-zone_pinky_bottom
          shift: [0.5 * outline_width, -0.5 * outline_height]
        - ref: mirror_finger-zone_pinky_bottom
          shift: [-0.5 * outline_width, -0.5 * outline_height]

  fill:
    - name: fill-left
    - operation: add
      name: fill-right

  keys_outline:
    - what: rectangle
      where: true
      bound: false
      size: [outline_width, outline_height]
      corner: 2

  board:
    - name: keys_outline
    - operation: add
      name: fill

  complete:
    - name: board
    - operation: stack
      name: keys

pcbs:
  dyad-choc-v1:
    outlines:
      main:
        outline: board
    footprints:

      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: smd-diode
        where: true
        asym: source
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8.25, -1]
          rotate: 90


      mcu-left:
        what: nicenano
        params:
          orientation: "down"
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height -1]
          rotate: -90


      mcu-right:
        what: nicenano
        params:
          orientation: "down"
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height -1]
          rotate: 90

      battery-left: # todo sort to and from
        what: battery
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
          rotate: -90
        

      battery-right: # todo sort to and from
        what: battery
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
          rotate: 90

      power-switch-left: # todo sort to and from
        what: slider_reversible
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
        params:
          side: B
          reverse: false
          from: RAW
          to: POSITIVE

      power-switch-right: # todo sort to and from
        what: slider_reversible
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 15.5]
        params:
          side: B
          reverse: false
          from: RAW
          to: POSITIVE

      nice-view-left:
        what: niceview
        where:
          ref:
            - finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height -20.5]
        adjust:
          rotate: 90
        params:
          outline: true
          side: 'F'
          MOSI: MOSI
          SCK: SCK
          VCC: VCC
          GND: GND
          CS: CS
      
      nice-view-right:
        what: niceview
        where:
          ref:
            - mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height -20.5]
        adjust:
          rotate: -90
        params:
          outline: true
          side: 'F'
          MOSI: MOSI
          SCK: SCK
          VCC: VCC
          GND: GND
          CS: CS
      
      reset-left:
        what: b3u1000p
        where:
          - ref: finger-zone_inner_home
            shift: [key_width + mcu_padding_width, mcu_position_height -27]
            rotate: 180
        params:
          r1: GND
          r2: RST
          reverse: false

      reset-right:
        what: b3u1000p
        where:
          - ref: mirror_finger-zone_inner_home
            shift: [key_width + mcu_padding_width, mcu_position_height -27]
            rotate: -180
        params:
          r1: GND
          r2: RST
          reverse: false

      # MCU Left
      via-gnd-1: 
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 5.8, mcu_position_height + 9.2]
        params:
          net: GND

      via-gnd-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 2.6, mcu_position_height + 9.2]
        params:
          net: GND

      via-row0-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 4.3, mcu_position_height + 11.52]
        params:
          net: ROW0

      via-row0-2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 4.3, mcu_position_height - 7.3]
        params:
          net: ROW0

      via-cs-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 5, mcu_position_height + 13]
        params:
          net: CS

      via-mosi-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 5.1, mcu_position_height + 2.8]
        params:
          net: MOSI

      via-sck-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 2.6, mcu_position_height + 0.3]
        params:
          net: SCK

      via-raw-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 3.3, mcu_position_height + 13]
        params:
          net: RAW

      via-positive-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 0.3, mcu_position_height + 13]
        params:
          net: POSITIVE

      via-vcc-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 5.3]
        params:
          net: VCC

      via-row1-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 5.8, mcu_position_height + 1.6]
        params:
          net: ROW1

      # Lower Section Left
      via_reset-1:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 6.4, mcu_position_height - 27]
        params:
          net: RST

      via_col4_1:
        what: via
        where:
          ref: thumb-zone_outer_sole
          shift: [-5.8 , 5.7]
        params:
          net: COL4

      via_col4_2:
        what: via
        where:
          ref: finger-zone_inner_bottom
          shift: [-3.25 , 3.6]
        params:
          net: COL4

      # via_col3_1:
      #   what: via
      #   where:
      #     ref: thumb-zone_inner_sole
      #     shift: [-5.8 , 5.7]
      #   params:
      #     net: COL3

      via_col3_2:
        what: via
        where:
          ref: finger-zone_index_bottom
          shift: [-3.25 , 3.6]
        params:
          net: COL3

      via_col0_1:
        what: via
        where:
          ref: finger-zone_pinky_bottom
          shift: [-3.25 , 8.2]
        params:
          net: COL0

      via_col1_1:
        what: via
        where:
          ref: finger-zone_ring_bottom
          shift: [-3.25 , 8.2]
        params:
          net: COL1

      via_col2_1:
        what: via
        where:
          ref: finger-zone_middle_bottom
          shift: [-3.25 , 8.2]
        params:
          net: COL2

      via_col2_2:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width -11.3, mcu_position_height - 1]
        params:
          net: COL2

      via_col1_3:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width -10.5, mcu_position_height - 2.5]
        params:
          net: COL1

      via_col0_3:
        what: via
        where:
          ref: finger-zone_inner_home
          shift: [key_width + mcu_padding_width -9.7, mcu_position_height - 4]
        params:
          net: COL0

      # via_row1_1:
      #   what: via
      #   where:
      #     ref: finger-zone_ring_home
      #     shift: [ 0.5 * key_width - 2.5, -2.7]
      #   params:
      #     net: ROW1

      # via_row1_2:
      #   what: via
      #   where:
      #     ref: finger-zone_ring_bottom
      #     shift: [ 0.5 * key_width - 2.5 , 0.5 * key_height - 2]
      #   params:
      #     net: ROW1

      # MCU Left
      right_via-gnd-1: 
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 5.8, mcu_position_height + 9.2]
        params:
          net: GND

      right_via-gnd-2:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 2.6, mcu_position_height + 9.2]
        params:
          net: GND

      right_via-row0-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 4.3, mcu_position_height + 11.52]
        params:
          net: ROW0

      right_via-row0-2:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 4.3, mcu_position_height - 7.3]
        params:
          net: ROW0

      right_via-cs-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 5, mcu_position_height + 13]
        params:
          net: CS

      right_via-mosi-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 5.1, mcu_position_height + 2.8]
        params:
          net: MOSI

      right_via-sck-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 2.6, mcu_position_height + 0.3]
        params:
          net: SCK

      right_via-raw-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 3.3, mcu_position_height + 13]
        params:
          net: RAW

      right_via-positive-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 0.3, mcu_position_height + 13]
        params:
          net: POSITIVE

      right_via-vcc-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width, mcu_position_height + 5.3]
        params:
          net: VCC

      right_via-row1-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width - 5.8, mcu_position_height + 1.6]
        params:
          net: ROW1

      # Lower Section Left
      right_via_reset-1:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [key_width + mcu_padding_width + 6.4, mcu_position_height - 27]
        params:
          net: RST

      right_via_col4_1:
        what: via
        where:
          ref: mirror_thumb-zone_outer_sole
          shift: [5.8 , 5.7]
        params:
          net: COL4

      right_via_col4_2:
        what: via
        where:
          ref: mirror_finger-zone_inner_bottom
          shift: [3.25 , 3.6]
        params:
          net: COL4

      # via_col3_1:
      #   what: via
      #   where:
      #     ref: thumb-zone_inner_sole
      #     shift: [-5.8 , 5.7]
      #   params:
      #     net: COL3

      right_via_col3_2:
        what: via
        where:
          ref: mirror_finger-zone_index_bottom
          shift: [3.25 , 3.6]
        params:
          net: COL3

      right_via_col0_1:
        what: via
        where:
          ref: mirror_finger-zone_pinky_bottom
          shift: [3.25 , 8.2]
        params:
          net: COL0

      right_via_col1_1:
        what: via
        where:
          ref: mirror_finger-zone_ring_bottom
          shift: [3.25 , 8.2]
        params:
          net: COL1

      right_via_col2_1:
        what: via
        where:
          ref: mirror_finger-zone_middle_bottom
          shift: [3.25 , 8.2]
        params:
          net: COL2

      right_via_col2_2:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [(key_width + mcu_padding_width -11.3) * -1, mcu_position_height - 1]
        params:
          net: COL2

      right_via_col1_3:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [(key_width + mcu_padding_width -10.5) * -1, mcu_position_height - 2.5]
        params:
          net: COL1

      right_via_col0_3:
        what: via
        where:
          ref: mirror_finger-zone_inner_home
          shift: [(key_width + mcu_padding_width -9.7) * -1, mcu_position_height - 4]
        params:
          net: COL0

      # via_row1_1:
      #   what: via
      #   where:
      #     ref: finger-zone_ring_home
      #     shift: [ 0.5 * key_width - 2.5, -2.7]
      #   params:
      #     net: ROW1

      # via_row1_2:
      #   what: via
      #   where:
      #     ref: finger-zone_ring_bottom
      #     shift: [ 0.5 * key_width - 2.5 , 0.5 * key_height - 2]
      #   params:
      #     net: ROW1
